# Generated by Django 4.0.5 on 2022-12-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='slug',
            field=models.CharField(blank=True, max_length=85, null=True),
        ),
    ]
