# Generated by Django 4.0.5 on 2022-12-10 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_entry_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='slug',
            new_name='entry_slug',
        ),
    ]
