# Generated by Django 4.0.5 on 2022-12-11 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_rename_slug_entry_entry_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', models.CharField(blank=True, max_length=85, null=True)),
                ('likes_to_the_comment', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commented_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.entry')),
            ],
        ),
    ]
