# Generated by Django 4.0.5 on 2022-12-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0004_entrycomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrycomments',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Yurtdışına çıkmadan yapılması gerekenler'),
        ),
    ]
