# Generated by Django 4.0.5 on 2022-12-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0005_alter_entrycomments_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrycomments',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
