# Generated by Django 4.0.5 on 2022-12-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0006_alter_entrycomments_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrycomments',
            name='likes_to_the_comment',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
